# Generated by Django 6.0.3 on 2026-03-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
    ]
