# Generated by Django 6.0.3 on 2026-03-30 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0003_hybrid_algorithm_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionresult",
            name="decision_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="edge_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="entropy_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="final_label",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="kmeans_variance",
        ),
    ]
