# Generated by Django 6.0.3 on 2026-04-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0005_v2_hybrid_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionresult",
            name="color_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="decision_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="edge_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="entropy_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="freq_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="kmeans_variance",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="lbp_score",
        ),
        migrations.RemoveField(
            model_name="detectionresult",
            name="verdict",
        ),
    ]
